### PR TITLE
Consolidate dependency fixes

### LINKED ISSUE #408: Dependency Dashboard
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Rate-Limited

These updates are currently rate-limited. Click on a checkbox below to force their creation now.

 - [ ] Update dependency ajv to v8.11.2
 - [ ] Update dependency chai to v4.3.7
 - [ ] Update buildkite plugin docker-compose to v3.13.0
 - [ ] Update Node.js to v19
 - [ ] Update buildkite plugin docker-compose to v4
 - [ ] Update dependency fs-extra to v11
 - [ ] 🔐 **Create all rate-limited PRs at once** 🔐

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [Update dependency minimatch to 3.0.5 [SECURITY]](../pull/446)
 - [ ] [Update Node.js to a136ed7](../pull/443)
 - [ ] [Update dependency compare-versions to v4.1.4](../pull/444)
 - [ ] [Update dependency mocha to v9.2.2](../pull/425)
 - [ ] [Update dependency isomorphic-git to v1.21.0](../pull/440)
 - [ ] [Update dependency compare-versions to v5](../pull/445)
 - [ ] [Update dependency eslint-plugin-promise to v6](../pull/433)
 - [ ] [Update dependency mocha to v10](../pull/435)
 - [ ] [Update dependency standard to v17](../pull/436)
 - [ ] [Update dependency tap to v16](../pull/438)
 - [ ] [Update dependency yargs to v17](../pull/441)
 - [ ] **Click on this checkbox to rebase all open PRs at once**

## Ignored or Blocked

These are blocked by an existing closed PR and will not be recreated unless you click a checkbox below.

 - [ ] [Update dependency lodash to 4.17.21 [SECURITY]](../pull/421)
 - [ ] [Update dependency js-yaml to v4](../pull/391)

## Detected dependencies

<details><summary>buildkite</summary>
<blockquote>

<details><summary>.buildkite/pipeline.deploy.yml</summary>

 - `docker-compose v3.10.0`
 - `docker-login v2.1.0`
 - `docker-compose v3.10.0`
 - `docker-login v2.1.0`
 - `docker-compose v3.10.0`

</details>

<details><summary>.buildkite/pipeline.yml</summary>

 - `docker-compose v3.10.0`
 - `docker-compose v3.10.0`

</details>

</blockquote>
</details>

<details><summary>docker-compose</summary>
<blockquote>

<details><summary>docker-compose.prod.yml</summary>

</details>

<details><summary>docker-compose.yml</summary>

</details>

</blockquote>
</details>

<details><summary>dockerfile</summary>
<blockquote>

<details><summary>Dockerfile</summary>

 - `node 18-alpine@sha256:b3ca07adf425d043e180464aac97cb4f7a566651f77f4ecb87b10c10788644bb`

</details>

</blockquote>
</details>

<details><summary>npm</summary>
<blockquote>

<details><summary>package.json</summary>

 - `ajv 8.11.0`
 - `compare-versions 4.1.3`
 - `isomorphic-git 1.19.0`
 - `js-yaml 3.14.1`
 - `tap 14.11.0`
 - `yargs 15.4.1`
 - `chai 4.3.6`
 - `eslint-config-standard 17.0.0`
 - `eslint-plugin-import 2.26.0`
 - `eslint-plugin-node 11.1.0`
 - `eslint-plugin-promise 4.3.1`
 - `eslint-plugin-standard 4.1.0`
 - `fs-extra 10.1.0`
 - `mocha 9.2.0`
 - `standard 14.3.4`

</details>

</blockquote>
</details>

---

- [ ] Check this box to trigger a request for Renovate to run again on this repository

### PR DESCRIPTION
**Pull request by toote**
This takes care of updating all dependencies:

* NodeJS 18-alpine image base to latest one (same as #443)
* ajv: 8.11.0 -> 8.11.2 (required some minor tuning of the code to avoid deprecation errors and unnecessary warnings)
* compare-versions: 4.1.3 -> 5.0.1 (same as #445, that superseeds #430)
* isomorphic-git: 1.19.0 -> 1.21.0 (same as #440)
* tap: 14.11.0 -> 16.3.2 (same as #438)
* yargs: 15.4.1 -> 17.6.2 (same as #441)
* fs-extra: 10.1.0 -> 11.1.0 (to get rid of some vulnerability warnings during audit, taking care of #446)
* mocha 9.2.0 -> 10.2.0 (same as #435, that superseeds #425)
* standard: 14.3.4 -> 17.0.0 (same as #436, also depends on `eslint-plugin-*` packages so they were removed, taking care of #433)

While I was at it, I also deactivated the dependency dashboard (closes #408)

### CODE REVIEW

File: lib/linters/readme-version-number-linter.js [hunk 1]
```diff
@@ -14,12 +14,9 @@ module.exports = async function (argv, tap) {
...
   const sortedTags = tags.sort((t1, t2) => {
-    try {
-      return compareVersions(t1, t2)
-    } catch (err) {
-      // Ignore semver parsing errors
-      return -1
-    }
+    if (!validate(t1)) { return -1 } // invalid t1 < whatever t2 (makes sort stable)
+    if (!validate(t2)) { return 1 } // invalid t2 < valid t1
+    return compareVersions(t1, t2) // both are valid, let the module decide
```
Comment (pzeballos) [inline lib/linters/readme-version-number-linter.js:19]: nice!

**Review by pzeballos — APPROVED** [review]
💚
